### ISSUE TITLE
Ensure the UI is consistent across devices

### ISSUE THREAD

**Issue by aclissold** [aclissold/twyst#2]

**Comment by dannysepler** [comment]
are there specific ones we're worried about? how about ipad?

**Comment by aclissold** [comment]
I already know for a fact that it's screwy on a 6 Plus because we're size based on the screen height, which stretches some images and not the others. I think the right solution is to use container nodes to handle the tap target and center the images within them.

**Comment by aclissold** [comment]
The accidental buttons are different than the note buttons lol and the logo is definitely not where we want it!
![simulator screen shot sep 16 2015 1 32 19 am](https://cloud.githubusercontent.com/assets/4397642/9897117/c6f3aa54-5c12-11e5-8d78-9af2baa70c63.png)

**Comment by aclissold** [comment]
Oh, but we're not supporting iPad so we don't have to worry about that one, just the various iPhone sizes.

**Comment by aclissold** [comment]
Closed via 24196f03428d6abc38919ab3b53f6fd51920c779.
