### ISSUE TITLE
A "clicking" sound can be heard when starting/stopping a note

### ISSUE THREAD

**Issue by aclissold** [aclissold/twyst#3]

**Comment by dannysepler** [comment]
I actually think this is okay. In fact, after we were playing around with the app for a bit, I was starting to like this!

**Comment by aclissold** [comment]
I agree that you get used to it and it sounds kinda neat! But I instantly recognize this sound as meaning that the waveform is corrupted. It's a very unnatural sound. Oh but this makes me think, we could definitely have different instruments that intentionally have a strong attack like this built into the ADSR. I just made #8 to track that haha.

**Comment by aclissold** [comment]
I should be able to fix this when I switch the underlying technology away from AudioKit.

**Comment by aclissold** [comment]
Yup! The new [synthesis functions](https://github.com/aclissold/twyst/blob/ab9b8643f6d6032442f51cc7412ef233ddaad1bb/Twyst/SynthFunctions.m) avoid this problem by using a very fast, but not instant, attack rate.
